-- Run this SQL in your Supabase SQL Editor (https://supabase.com/dashboard/project/folmshmlzrruurqcyqre/sql)

CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  phone_number TEXT NOT NULL,
  delivery_address TEXT NOT NULL,
  day TEXT NOT NULL,
  meal TEXT NOT NULL,
  friday_option TEXT,
  quantity INT DEFAULT 1,
  unit_price NUMERIC DEFAULT 120,
  total_price NUMERIC DEFAULT 120,
  special_instructions TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts so customers can submit orders from the website
CREATE POLICY "Allow public insert to orders" 
ON public.orders 
FOR INSERT 
TO anon 
WITH CHECK (true);

-- Allow reading orders (for owner / dashboard)
CREATE POLICY "Allow public read access to orders" 
ON public.orders 
FOR SELECT 
TO anon 
USING (true);
